/**
 * Board data model + loader. Pure (no `vscode`, no `fs` import) so it unit-tests
 * without the VS Code runtime — mirrors the `cockpit-html.ts` split. The host
 * reads the JSON and hands the parsed object to a `BoardSource`; the source
 * validates it and returns a typed `Board`.
 *
 * `SnapshotSource` is today's path (committed `atrium-board.json`, generated by
 * a Claude session via the Linear MCP). `LinearSdkSource` is the future live
 * path (`@linear/sdk` + API key) — stubbed so the seam exists now.
 */

export type Priority = "urgent" | "high" | "med" | "low";
export type TicketState = "todo" | "doing" | "review" | "done";
/** The full Linear status set (the status picker's options). `state` collapses
 *  these to the four kanban columns; `status` keeps the exact Linear status so
 *  Backlog/Canceled/Duplicate stay distinct (the kanban only has four columns). */
export type FullStatus = "Backlog" | "Todo" | "In Progress" | "In Review" | "Done" | "Canceled" | "Duplicate";
export type ActivityKind = "pickup" | "plan" | "phase" | "close" | "commit";

export interface TestSummary {
  passed: number;
  failed: number;
  missing: number;
  /** False until real test discovery runs (STO-2186); UI shows "not discovered". */
  discovered: boolean;
}

export interface ActivityItem {
  kind: ActivityKind;
  text: string;
  when: string;
}

export interface Ticket {
  id: string;
  title: string;
  url: string;
  priority: Priority;
  state: TicketState;
  spec: string[];
  tests: TestSummary;
  activity: ActivityItem[];
  /** Exact Linear status (Backlog…Duplicate) — drives the modal status picker and
   *  marks Canceled/Duplicate tickets (which `state` can't represent). Live pull
   *  only; absent in the committed snapshot, where `state` is the only signal. */
  status?: FullStatus;
  /** Full Linear description markdown — rendered in the ticket modal (STO-2494).
   *  Live pull only; absent in the committed snapshot. */
  description?: string;
  /** Linear's internal issue UUID — present only on a live pull; the write-back
   *  (STO-2469/2470) targets this. Absent in the committed snapshot. */
  linearId?: string;
  /** Linear sortOrder (priority within the project) — drives kanban ordering and
   *  is the write target for drag-to-reorder (STO-2470). Live pull only. */
  sortOrder?: number;
}

export interface Wave {
  name: string;
  label: string;
  /** Furthest pipeline stage this wave reached (plan…release). */
  stage: string;
  /** UAT loop-back count; 1 = no bounce. */
  passN: number;
  /** Spike code blocking this wave (e.g. "T-110"), or null. */
  gatedBy: string | null;
  /** Short "what this wave entails" blurb — the wave's Linear label description,
   *  shown succinctly on the board and editable/synced back (STO-2574). Live only. */
  description?: string;
  /** The wave label's Linear id — the write target for the description sync. Live only. */
  labelId?: string;
  tickets: Ticket[];
}

export interface Spike {
  id: string;
  code: string;
  gatesWave: string;
  state: TicketState;
}

export interface Board {
  project: string;
  generatedAt: string;
  spikes: Spike[];
  waves: Wave[];
}

export interface BoardSource {
  load(): Promise<Board>;
}

const PRIORITIES = new Set<Priority>(["urgent", "high", "med", "low"]);
const STATES = new Set<TicketState>(["todo", "doing", "review", "done"]);
const KINDS = new Set<ActivityKind>(["pickup", "plan", "phase", "close", "commit"]);

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function fail(msg: string): never {
  throw new Error(`Invalid atrium-board: ${msg}`);
}

function validateTests(raw: unknown, where: string): TestSummary {
  if (!isObject(raw)) fail(`${where}.tests must be an object`);
  for (const k of ["passed", "failed", "missing"] as const) {
    if (typeof raw[k] !== "number") fail(`${where}.tests.${k} must be a number`);
  }
  if (typeof raw.discovered !== "boolean") fail(`${where}.tests.discovered must be a boolean`);
  return raw as unknown as TestSummary;
}

function validateActivity(raw: unknown, where: string): ActivityItem {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (!KINDS.has(raw.kind as ActivityKind)) fail(`${where}.kind "${String(raw.kind)}" is invalid`);
  if (typeof raw.text !== "string") fail(`${where}.text must be a string`);
  if (typeof raw.when !== "string") fail(`${where}.when must be a string`);
  return raw as unknown as ActivityItem;
}

function validateTicket(raw: unknown, where: string): Ticket {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.id !== "string") fail(`${where}.id must be a string`);
  if (typeof raw.title !== "string") fail(`${where}.title must be a string`);
  if (typeof raw.url !== "string") fail(`${where}.url must be a string`);
  if (!PRIORITIES.has(raw.priority as Priority)) fail(`${where}.priority "${String(raw.priority)}" is invalid`);
  if (!STATES.has(raw.state as TicketState)) fail(`${where}.state "${String(raw.state)}" is invalid`);
  if (!Array.isArray(raw.spec) || raw.spec.some((s) => typeof s !== "string"))
    fail(`${where}.spec must be a string[]`);
  validateTests(raw.tests, where);
  if (!Array.isArray(raw.activity)) fail(`${where}.activity must be an array`);
  raw.activity.forEach((a, i) => validateActivity(a, `${where}.activity[${i}]`));
  if (raw.linearId !== undefined && typeof raw.linearId !== "string")
    fail(`${where}.linearId must be a string when present`);
  if (raw.sortOrder !== undefined && typeof raw.sortOrder !== "number")
    fail(`${where}.sortOrder must be a number when present`);
  return raw as unknown as Ticket;
}

function validateWave(raw: unknown, where: string): Wave {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.name !== "string") fail(`${where}.name must be a string`);
  if (typeof raw.label !== "string") fail(`${where}.label must be a string`);
  if (typeof raw.stage !== "string") fail(`${where}.stage must be a string`);
  if (typeof raw.passN !== "number") fail(`${where}.passN must be a number`);
  if (raw.gatedBy !== null && typeof raw.gatedBy !== "string")
    fail(`${where}.gatedBy must be a string or null`);
  if (!Array.isArray(raw.tickets)) fail(`${where}.tickets must be an array`);
  raw.tickets.forEach((t, i) => validateTicket(t, `${where}.tickets[${i}]`));
  return raw as unknown as Wave;
}

function validateSpike(raw: unknown, where: string): Spike {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.id !== "string") fail(`${where}.id must be a string`);
  if (typeof raw.code !== "string") fail(`${where}.code must be a string`);
  if (typeof raw.gatesWave !== "string") fail(`${where}.gatesWave must be a string`);
  if (!STATES.has(raw.state as TicketState)) fail(`${where}.state "${String(raw.state)}" is invalid`);
  return raw as unknown as Spike;
}

/** Validates an untrusted parsed object into a typed `Board`. Throws on any
 *  structural problem so the host can fall back to an empty board + error. */
export function validateBoard(raw: unknown): Board {
  if (!isObject(raw)) fail("root must be an object");
  if (typeof raw.project !== "string") fail("project must be a string");
  if (typeof raw.generatedAt !== "string") fail("generatedAt must be a string");
  if (!Array.isArray(raw.spikes)) fail("spikes must be an array");
  if (!Array.isArray(raw.waves)) fail("waves must be an array");
  raw.spikes.forEach((s, i) => validateSpike(s, `spikes[${i}]`));
  raw.waves.forEach((w, i) => validateWave(w, `waves[${i}]`));
  return raw as unknown as Board;
}

/** Today's default source: a committed JSON snapshot handed in already-parsed. */
export class SnapshotSource implements BoardSource {
  constructor(private readonly raw: unknown) {}
  async load(): Promise<Board> {
    return validateBoard(this.raw);
  }
}

/** Empty board for the error-fallback path (malformed/missing snapshot). */
export const EMPTY_BOARD: Board = { project: "", generatedAt: "", spikes: [], waves: [] };

// ── Pure Linear → Board mapping (shared by the live source; SDK-free so it
//    unit-tests without pulling @linear/sdk) ──────────────────────────────────

/** The flattened shape the live source extracts from a Linear issue. */
export interface LinearIssueLite {
  /** Linear's internal UUID (write target). */
  id: string;
  identifier: string;
  title: string;
  url: string;
  priority: number;
  sortOrder: number;
  stateType: string;
  stateName: string;
  labels: string[];
  /** Per-label id + description (live pull) — lets a wave carry its label's
   *  description + write-target id (STO-2574). Names still live in `labels`. */
  labelInfo?: { name: string; id: string; description: string | null }[];
  description: string | null;
  comments: { body: string; createdAt: string }[];
}

/** Default wave-label prefix. A Linear label starting with this (case-insensitive)
 *  is treated as a wave/sprint. Overridable via the `atrium.linear.wavePrefix`
 *  setting so the cockpit works with any labelling convention without a rebuild. */
export const DEFAULT_WAVE_PREFIX = "ATR Wave";

/** The `wavePrefix` setting, parsed: comma-separated list of prefixes
 *  (back-compat: a single string is a one-entry list; empty → default). */
export function parsePrefixes(setting?: string): string[] {
  const list = (setting ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  return list.length > 0 ? list : [DEFAULT_WAVE_PREFIX];
}

/** Generic sprint-ish label heuristic (STO-2495): a wave/sprint/phase/slice/
 *  milestone word followed by a number ("sprint-12", "CG Phase 3", "SS Wave 7")
 *  or a single letter ("CG Sprint A: Launch Blockers"). Deliberately
 *  conservative — bare "P4"-style codes stay Unsorted rather than risk false
 *  positives. */
const SPRINTISH = /\b(wave|sprint|phase|slice|milestone)([ \-_]?\d+(\.\d+)?|[ -][a-z](?=[\s:.,)]|$))/i;

/**
 * Wave-label matcher for a project's label set (STO-2495). Configured prefixes
 * are authoritative when ANY label in the project matches one; otherwise —
 * a foreign project with its own naming convention — the sprint-ish heuristic
 * takes over, so the board groups with zero config.
 */
export function makeWaveLabelMatcher(
  prefixSetting: string | undefined,
  allLabels: string[],
): (label: string) => boolean {
  const prefixes = parsePrefixes(prefixSetting).map((p) => p.toLowerCase());
  const byPrefix = (label: string) => {
    const l = label.trim().toLowerCase();
    return prefixes.some((p) => l.startsWith(p));
  };
  if (allLabels.some(byPrefix)) return byPrefix;
  return (label: string) => SPRINTISH.test(label);
}

/** Display name for a wave label: drops a leading "ATR " so "ATR Wave 5 · SDLC
 *  flow" reads "Wave 5 · SDLC flow". Whatever you label it in Linear is the name. */
export function waveName(label: string): string {
  return label.replace(/^ATR\s+/i, "").trim() || label;
}

/** Sort key for a wave label: the first number in it (e.g. "ATR Wave 4.5" → 4.5).
 *  Labels with no number sort last. */
export function waveOrder(label: string): number {
  const m = label.match(/(\d+(?:\.\d+)?)/);
  return m ? parseFloat(m[1]) : Number.POSITIVE_INFINITY;
}

export function mapPriority(p: number): Priority {
  return p === 1 ? "urgent" : p === 2 ? "high" : p === 3 ? "med" : "low";
}

export function mapState(stateType: string, stateName = ""): TicketState {
  if (stateType === "completed") return "done";
  if (stateType === "started") return /review/i.test(stateName) ? "review" : "doing";
  return "todo"; // backlog / unstarted / canceled / triage all park in the To-do column
}

/** The exact Linear status, for the modal picker + Canceled/Duplicate marking.
 *  Linear's "Duplicate" is a `canceled`-type state distinguished only by name. */
export function fullStatus(stateType: string, stateName = ""): FullStatus {
  if (stateType === "completed") return "Done";
  if (stateType === "canceled") return /duplicate/i.test(stateName) ? "Duplicate" : "Canceled";
  if (stateType === "started") return /review/i.test(stateName) ? "In Review" : "In Progress";
  if (stateType === "backlog") return "Backlog";
  return "Todo";
}

/** Canceled or Duplicate — terminal statuses excluded from the kanban, progress
 *  counts and (by default) the wave lists. The status picker can restore them. */
export function isCanceled(t: { status?: FullStatus }): boolean {
  return t.status === "Canceled" || t.status === "Duplicate";
}

/** Every bullet line (-, *, or "1.") with its marker stripped. Uncapped since
 *  STO-2494 — the Plan view shows the full criteria list. */
export function specFromDescription(description: string | null): string[] {
  if (!description) return [];
  return description
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => /^([-*]|\d+\.)\s+/.test(l))
    .map((l) => l.replace(/^([-*]|\d+\.)\s+/, "").replace(/^\[[ x]\]\s*/i, "").trim())
    .filter(Boolean);
}

/** Maps a comment body onto an audit-trail kind by keyword (first match wins).
 *  Our real comments don't use rigid `Pickup:` headers, so this is heuristic. */
const KIND_PATTERNS: [ActivityKind, RegExp][] = [
  ["close", /\b(clos|merg|shipped|follow-?up)/i],
  ["plan", /\b(plan|approach|locked)\b/i],
  ["pickup", /\b(start|pick(ing|ed)? up|kick(ing|ed)? off)/i],
  ["phase", /\b(complete|done|slice|phase|implement|uat|blocked|verif|fix)/i],
];

function kindOfComment(body: string): ActivityKind {
  for (const [kind, re] of KIND_PATTERNS) if (re.test(body)) return kind;
  return "phase";
}

/** First non-empty line of a comment, stripped of markdown emphasis, truncated. */
function firstLine(body: string): string {
  const line = body.split("\n").map((l) => l.trim()).find((l) => l.length > 0) ?? "";
  const plain = line.replace(/[*_`#]/g, "").trim();
  return plain.length > 90 ? `${plain.slice(0, 87)}…` : plain;
}

/** Derives the audit-trail activity (Pickup / Plan / Phase / Close) from a
 *  ticket's Linear comments. Pure — drives the audit ribbon (STO-2172) and the
 *  ticket Activity tab. */
export function activityFromComments(comments: { body: string; createdAt: string }[]): ActivityItem[] {
  return comments.map((c) => ({ kind: kindOfComment(c.body), text: firstLine(c.body), when: c.createdAt.slice(0, 10) }));
}

function issueToTicket(i: LinearIssueLite): Ticket {
  return {
    id: i.identifier,
    title: i.title,
    url: i.url,
    priority: mapPriority(i.priority),
    state: mapState(i.stateType, i.stateName),
    status: fullStatus(i.stateType, i.stateName),
    spec: specFromDescription(i.description),
    tests: { passed: 0, failed: 0, missing: 0, discovered: false },
    activity: activityFromComments(i.comments),
    description: i.description ?? undefined,
    linearId: i.id,
    sortOrder: i.sortOrder,
  };
}

/**
 * Derives a wave's pipeline stage from its ticket states (STO-2476): all done →
 * `release`; any active (doing/review) → `build`; otherwise (nothing started) →
 * `plan`. The `fallback` (the WAVE_META stage) is used only for an empty wave.
 * Design/UX/UAT stages are conditional and not derived here (STO-2477).
 */
export function deriveStage(tickets: Ticket[], fallback: string): string {
  // Canceled/Duplicate tickets don't count toward a wave's progress or stage.
  const active = tickets.filter((t) => !isCanceled(t));
  if (active.length === 0) return fallback;
  if (active.every((t) => t.state === "done")) return "release";
  if (active.some((t) => t.state === "doing" || t.state === "review")) return "build";
  return "plan";
}

/**
 * Builds the Board by **detecting waves dynamically from the labels on ACTIVE
 * tickets** — any label starting with `wavePrefix` (default "ATR Wave") that an
 * active ticket carries becomes a wave, sorted by number, named from the label,
 * stage derived from states. Waves are never created up front: a label carried
 * only by canceled/duplicate tickets makes no (blank) wave. Canceled/Duplicate
 * issues are kept (flagged via `status`) and attached to the waves that exist, so
 * the filter can reveal them and the status picker can restore them — hidden by
 * default, excluded from counts. Active issues with no wave label fall into an
 * "Unsorted" bucket. Works for any Linear project, even one never set up with
 * Atrium's labels (everything lands in Unsorted, sync still works). Pure.
 */
export function boardFromIssues(
  issues: LinearIssueLite[],
  opts: { projectName: string; generatedAt: string; wavePrefix?: string },
): Board {
  const live = issues;
  // Waves emerge from EXISTING (active) tickets — never created up front. Detection
  // ignores canceled/duplicate issues, so an old label carried only by canceled
  // tickets makes no blank wave; canceled tickets still attach to waves that exist.
  const active = issues.filter((i) => i.stateType !== "canceled");
  // Prefix(es) win when present; foreign conventions fall back to the sprint-ish
  // heuristic (STO-2495) over the labels actually on active tickets in this project.
  const allLabels = Array.from(new Set(active.flatMap((i) => i.labels)));
  const isWaveLabel = makeWaveLabelMatcher(opts.wavePrefix, allLabels);

  // The distinct wave labels on active issues, in wave-number order.
  const waveLabels = Array.from(new Set(active.flatMap((i) => i.labels.filter(isWaveLabel)))).sort(
    (a, b) => waveOrder(a) - waveOrder(b) || a.localeCompare(b),
  );

  // label name → {id, description} from the live pull, so a wave can carry its
  // label's blurb + write-target id (STO-2574). Absent in snapshot mode.
  const labelMeta = new Map<string, { id: string; description: string | null }>();
  for (const i of live) for (const l of i.labelInfo ?? []) labelMeta.set(l.name, { id: l.id, description: l.description });

  const waves: Wave[] = waveLabels.map((label) => {
    // Attach all tickets carrying the label, incl. canceled (revealed via filter).
    const tickets = live.filter((i) => i.labels.includes(label)).map(issueToTicket);
    const meta = labelMeta.get(label);
    return {
      name: waveName(label),
      label,
      stage: deriveStage(tickets, "plan"),
      passN: 1,
      gatedBy: null,
      description: meta?.description ?? undefined,
      labelId: meta?.id,
      tickets,
    };
  });

  // Label-less work still shows in an Unsorted bucket — but only when there's
  // ACTIVE orphan work, so a project of only-canceled stragglers stays blank-free.
  const isOrphan = (i: LinearIssueLite) => !i.labels.some(isWaveLabel);
  if (active.some(isOrphan)) {
    waves.push({
      name: "Unsorted · No sprint",
      label: "",
      stage: "",
      passN: 1,
      gatedBy: null,
      tickets: live.filter(isOrphan).map(issueToTicket),
    });
  }

  return { project: opts.projectName, generatedAt: opts.generatedAt, spikes: [], waves };
}
