/**
 * Board data model + loader. Pure (no `vscode`, no `fs` import) so it unit-tests
 * without the VS Code runtime — mirrors the `cockpit-html.ts` split. The host
 * reads the JSON and hands the parsed object to a `BoardSource`; the source
 * validates it and returns a typed `Board`.
 *
 * `SnapshotSource` is today's path (committed `atrium-board.json`, generated by
 * a Claude session via the Linear MCP). `LinearSdkSource` is the future live
 * path (`@linear/sdk` + API key) — stubbed so the seam exists now.
 */

export type Priority = "urgent" | "high" | "med" | "low";
export type TicketState = "todo" | "doing" | "review" | "done";
export type ActivityKind = "pickup" | "plan" | "phase" | "close" | "commit";

export interface TestSummary {
  passed: number;
  failed: number;
  missing: number;
  /** False until real test discovery runs (STO-2186); UI shows "not discovered". */
  discovered: boolean;
}

export interface ActivityItem {
  kind: ActivityKind;
  text: string;
  when: string;
}

export interface Ticket {
  id: string;
  title: string;
  url: string;
  priority: Priority;
  state: TicketState;
  spec: string[];
  tests: TestSummary;
  activity: ActivityItem[];
}

export interface Wave {
  name: string;
  label: string;
  /** Furthest pipeline stage this wave reached (plan…release). */
  stage: string;
  /** UAT loop-back count; 1 = no bounce. */
  passN: number;
  /** Spike code blocking this wave (e.g. "T-110"), or null. */
  gatedBy: string | null;
  tickets: Ticket[];
}

export interface Spike {
  id: string;
  code: string;
  gatesWave: string;
  state: TicketState;
}

export interface Board {
  project: string;
  generatedAt: string;
  spikes: Spike[];
  waves: Wave[];
}

export interface BoardSource {
  load(): Promise<Board>;
}

const PRIORITIES = new Set<Priority>(["urgent", "high", "med", "low"]);
const STATES = new Set<TicketState>(["todo", "doing", "review", "done"]);
const KINDS = new Set<ActivityKind>(["pickup", "plan", "phase", "close", "commit"]);

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function fail(msg: string): never {
  throw new Error(`Invalid atrium-board: ${msg}`);
}

function validateTests(raw: unknown, where: string): TestSummary {
  if (!isObject(raw)) fail(`${where}.tests must be an object`);
  for (const k of ["passed", "failed", "missing"] as const) {
    if (typeof raw[k] !== "number") fail(`${where}.tests.${k} must be a number`);
  }
  if (typeof raw.discovered !== "boolean") fail(`${where}.tests.discovered must be a boolean`);
  return raw as unknown as TestSummary;
}

function validateActivity(raw: unknown, where: string): ActivityItem {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (!KINDS.has(raw.kind as ActivityKind)) fail(`${where}.kind "${String(raw.kind)}" is invalid`);
  if (typeof raw.text !== "string") fail(`${where}.text must be a string`);
  if (typeof raw.when !== "string") fail(`${where}.when must be a string`);
  return raw as unknown as ActivityItem;
}

function validateTicket(raw: unknown, where: string): Ticket {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.id !== "string") fail(`${where}.id must be a string`);
  if (typeof raw.title !== "string") fail(`${where}.title must be a string`);
  if (typeof raw.url !== "string") fail(`${where}.url must be a string`);
  if (!PRIORITIES.has(raw.priority as Priority)) fail(`${where}.priority "${String(raw.priority)}" is invalid`);
  if (!STATES.has(raw.state as TicketState)) fail(`${where}.state "${String(raw.state)}" is invalid`);
  if (!Array.isArray(raw.spec) || raw.spec.some((s) => typeof s !== "string"))
    fail(`${where}.spec must be a string[]`);
  validateTests(raw.tests, where);
  if (!Array.isArray(raw.activity)) fail(`${where}.activity must be an array`);
  raw.activity.forEach((a, i) => validateActivity(a, `${where}.activity[${i}]`));
  return raw as unknown as Ticket;
}

function validateWave(raw: unknown, where: string): Wave {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.name !== "string") fail(`${where}.name must be a string`);
  if (typeof raw.label !== "string") fail(`${where}.label must be a string`);
  if (typeof raw.stage !== "string") fail(`${where}.stage must be a string`);
  if (typeof raw.passN !== "number") fail(`${where}.passN must be a number`);
  if (raw.gatedBy !== null && typeof raw.gatedBy !== "string")
    fail(`${where}.gatedBy must be a string or null`);
  if (!Array.isArray(raw.tickets)) fail(`${where}.tickets must be an array`);
  raw.tickets.forEach((t, i) => validateTicket(t, `${where}.tickets[${i}]`));
  return raw as unknown as Wave;
}

function validateSpike(raw: unknown, where: string): Spike {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.id !== "string") fail(`${where}.id must be a string`);
  if (typeof raw.code !== "string") fail(`${where}.code must be a string`);
  if (typeof raw.gatesWave !== "string") fail(`${where}.gatesWave must be a string`);
  if (!STATES.has(raw.state as TicketState)) fail(`${where}.state "${String(raw.state)}" is invalid`);
  return raw as unknown as Spike;
}

/** Validates an untrusted parsed object into a typed `Board`. Throws on any
 *  structural problem so the host can fall back to an empty board + error. */
export function validateBoard(raw: unknown): Board {
  if (!isObject(raw)) fail("root must be an object");
  if (typeof raw.project !== "string") fail("project must be a string");
  if (typeof raw.generatedAt !== "string") fail("generatedAt must be a string");
  if (!Array.isArray(raw.spikes)) fail("spikes must be an array");
  if (!Array.isArray(raw.waves)) fail("waves must be an array");
  raw.spikes.forEach((s, i) => validateSpike(s, `spikes[${i}]`));
  raw.waves.forEach((w, i) => validateWave(w, `waves[${i}]`));
  return raw as unknown as Board;
}

/** Today's default source: a committed JSON snapshot handed in already-parsed. */
export class SnapshotSource implements BoardSource {
  constructor(private readonly raw: unknown) {}
  async load(): Promise<Board> {
    return validateBoard(this.raw);
  }
}

/** Empty board for the error-fallback path (malformed/missing snapshot). */
export const EMPTY_BOARD: Board = { project: "", generatedAt: "", spikes: [], waves: [] };

// ── Pure Linear → Board mapping (shared by the live source; SDK-free so it
//    unit-tests without pulling @linear/sdk) ──────────────────────────────────

/** The flattened shape the live source extracts from a Linear issue. */
export interface LinearIssueLite {
  identifier: string;
  title: string;
  url: string;
  priority: number;
  stateType: string;
  stateName: string;
  labels: string[];
  description: string | null;
}

/** Wave label → display name + pipeline stage + gating spike. Single source of
 *  truth for grouping; keep in sync with the snapshot generator. */
const WAVE_META: { label: string; name: string; stage: string; gatedBy: string | null }[] = [
  { label: "ATR Wave 0", name: "Wave 0 · Visual layer", stage: "release", gatedBy: null },
  { label: "ATR Wave 0.5", name: "Wave 0.5 · Wave & ticket rail", stage: "build", gatedBy: null },
  { label: "ATR Wave 0.6 · Cockpit data", name: "Wave 0.6 · Cockpit data", stage: "build", gatedBy: null },
  { label: "ATR Wave 1", name: "Wave 1 · CLI bridge", stage: "plan", gatedBy: "T-110" },
  { label: "ATR Wave 2", name: "Wave 2 · Tool & permission cards", stage: "plan", gatedBy: "T-209" },
  { label: "ATR Wave 3", name: "Wave 3 · Composer extras", stage: "plan", gatedBy: "T-301" },
  { label: "ATR Wave 3.5", name: "Wave 3.5 · Plan & Design", stage: "plan", gatedBy: null },
  { label: "ATR Wave 4", name: "Wave 4 · Rails & palette", stage: "plan", gatedBy: null },
  { label: "ATR Wave 4.5", name: "Wave 4.5 · Pipeline & UAT", stage: "plan", gatedBy: null },
  { label: "ATR Wave 5", name: "Wave 5 · Settings & registry", stage: "plan", gatedBy: null },
  { label: "ATR Wave 7", name: "Wave 7 · History & search", stage: "plan", gatedBy: null },
  { label: "ATR Wave 8", name: "Wave 8 · Polish", stage: "plan", gatedBy: null },
];

const SPIKE_META: { id: string; code: string; gatesWave: string }[] = [
  { id: "STO-2146", code: "T-110", gatesWave: "Wave 1" },
  { id: "STO-2147", code: "T-209", gatesWave: "Wave 2" },
  { id: "STO-2115", code: "T-301", gatesWave: "Wave 3" },
];

export function mapPriority(p: number): Priority {
  return p === 1 ? "urgent" : p === 2 ? "high" : p === 3 ? "med" : "low";
}

export function mapState(stateType: string, stateName = ""): TicketState {
  if (stateType === "completed") return "done";
  if (stateType === "started") return /review/i.test(stateName) ? "review" : "doing";
  return "todo";
}

/** First 3 bullet lines (-, *, or "1.") with their markers stripped. */
export function specFromDescription(description: string | null): string[] {
  if (!description) return [];
  return description
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => /^([-*]|\d+\.)\s+/.test(l))
    .map((l) => l.replace(/^([-*]|\d+\.)\s+/, "").replace(/^\[[ x]\]\s*/i, "").trim())
    .filter(Boolean)
    .slice(0, 3);
}

function issueToTicket(i: LinearIssueLite): Ticket {
  return {
    id: i.identifier,
    title: i.title,
    url: i.url,
    priority: mapPriority(i.priority),
    state: mapState(i.stateType, i.stateName),
    spec: specFromDescription(i.description),
    tests: { passed: 0, failed: 0, missing: 0, discovered: false },
    activity: [],
  };
}

/** Groups live Linear issues into the same Board shape the snapshot produces.
 *  Canceled issues are dropped; empty waves are omitted. Pure. */
export function boardFromIssues(
  issues: LinearIssueLite[],
  opts: { projectName: string; generatedAt: string },
): Board {
  const live = issues.filter((i) => i.stateType !== "canceled");

  const waves: Wave[] = WAVE_META.map((meta) => ({
    name: meta.name,
    label: meta.label,
    stage: meta.stage,
    passN: 1,
    gatedBy: meta.gatedBy,
    tickets: live.filter((i) => i.labels.includes(meta.label)).map(issueToTicket),
  })).filter((w) => w.tickets.length > 0);

  // Anything without a recognized wave label still shows — never silently dropped.
  const known = new Set(WAVE_META.map((m) => m.label));
  const orphans = live.filter((i) => !i.labels.some((l) => known.has(l)));
  if (orphans.length > 0) {
    waves.push({
      name: "Unsorted · No sprint",
      label: "",
      stage: "",
      passN: 1,
      gatedBy: null,
      tickets: orphans.map(issueToTicket),
    });
  }

  const spikes: Spike[] = SPIKE_META.flatMap((meta) => {
    const issue = live.find((i) => i.identifier === meta.id);
    return issue
      ? [{ id: meta.id, code: meta.code, gatesWave: meta.gatesWave, state: mapState(issue.stateType, issue.stateName) }]
      : [];
  });

  return { project: opts.projectName, generatedAt: opts.generatedAt, spikes, waves };
}
