/**
 * Board data model + loader. Pure (no `vscode`, no `fs` import) so it unit-tests
 * without the VS Code runtime — mirrors the `cockpit-html.ts` split. The host
 * reads the JSON and hands the parsed object to a `BoardSource`; the source
 * validates it and returns a typed `Board`.
 *
 * `SnapshotSource` is today's path (committed `atrium-board.json`, generated by
 * a Claude session via the Linear MCP). `LinearSdkSource` is the future live
 * path (`@linear/sdk` + API key) — stubbed so the seam exists now.
 */

export type Priority = "urgent" | "high" | "med" | "low";
export type TicketState = "todo" | "doing" | "done";
export type ActivityKind = "pickup" | "plan" | "phase" | "close" | "commit";

export interface TestSummary {
  passed: number;
  failed: number;
  missing: number;
  /** False until real test discovery runs (STO-2186); UI shows "not discovered". */
  discovered: boolean;
}

export interface ActivityItem {
  kind: ActivityKind;
  text: string;
  when: string;
}

export interface Ticket {
  id: string;
  title: string;
  url: string;
  priority: Priority;
  state: TicketState;
  spec: string[];
  tests: TestSummary;
  activity: ActivityItem[];
}

export interface Wave {
  name: string;
  label: string;
  /** Furthest pipeline stage this wave reached (plan…release). */
  stage: string;
  /** UAT loop-back count; 1 = no bounce. */
  passN: number;
  /** Spike code blocking this wave (e.g. "T-110"), or null. */
  gatedBy: string | null;
  tickets: Ticket[];
}

export interface Spike {
  id: string;
  code: string;
  gatesWave: string;
  state: TicketState;
}

export interface Board {
  project: string;
  generatedAt: string;
  spikes: Spike[];
  waves: Wave[];
}

export interface BoardSource {
  load(): Board;
}

const PRIORITIES = new Set<Priority>(["urgent", "high", "med", "low"]);
const STATES = new Set<TicketState>(["todo", "doing", "done"]);
const KINDS = new Set<ActivityKind>(["pickup", "plan", "phase", "close", "commit"]);

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function fail(msg: string): never {
  throw new Error(`Invalid atrium-board: ${msg}`);
}

function validateTests(raw: unknown, where: string): TestSummary {
  if (!isObject(raw)) fail(`${where}.tests must be an object`);
  for (const k of ["passed", "failed", "missing"] as const) {
    if (typeof raw[k] !== "number") fail(`${where}.tests.${k} must be a number`);
  }
  if (typeof raw.discovered !== "boolean") fail(`${where}.tests.discovered must be a boolean`);
  return raw as unknown as TestSummary;
}

function validateActivity(raw: unknown, where: string): ActivityItem {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (!KINDS.has(raw.kind as ActivityKind)) fail(`${where}.kind "${String(raw.kind)}" is invalid`);
  if (typeof raw.text !== "string") fail(`${where}.text must be a string`);
  if (typeof raw.when !== "string") fail(`${where}.when must be a string`);
  return raw as unknown as ActivityItem;
}

function validateTicket(raw: unknown, where: string): Ticket {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.id !== "string") fail(`${where}.id must be a string`);
  if (typeof raw.title !== "string") fail(`${where}.title must be a string`);
  if (typeof raw.url !== "string") fail(`${where}.url must be a string`);
  if (!PRIORITIES.has(raw.priority as Priority)) fail(`${where}.priority "${String(raw.priority)}" is invalid`);
  if (!STATES.has(raw.state as TicketState)) fail(`${where}.state "${String(raw.state)}" is invalid`);
  if (!Array.isArray(raw.spec) || raw.spec.some((s) => typeof s !== "string"))
    fail(`${where}.spec must be a string[]`);
  validateTests(raw.tests, where);
  if (!Array.isArray(raw.activity)) fail(`${where}.activity must be an array`);
  raw.activity.forEach((a, i) => validateActivity(a, `${where}.activity[${i}]`));
  return raw as unknown as Ticket;
}

function validateWave(raw: unknown, where: string): Wave {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.name !== "string") fail(`${where}.name must be a string`);
  if (typeof raw.label !== "string") fail(`${where}.label must be a string`);
  if (typeof raw.stage !== "string") fail(`${where}.stage must be a string`);
  if (typeof raw.passN !== "number") fail(`${where}.passN must be a number`);
  if (raw.gatedBy !== null && typeof raw.gatedBy !== "string")
    fail(`${where}.gatedBy must be a string or null`);
  if (!Array.isArray(raw.tickets)) fail(`${where}.tickets must be an array`);
  raw.tickets.forEach((t, i) => validateTicket(t, `${where}.tickets[${i}]`));
  return raw as unknown as Wave;
}

function validateSpike(raw: unknown, where: string): Spike {
  if (!isObject(raw)) fail(`${where} must be an object`);
  if (typeof raw.id !== "string") fail(`${where}.id must be a string`);
  if (typeof raw.code !== "string") fail(`${where}.code must be a string`);
  if (typeof raw.gatesWave !== "string") fail(`${where}.gatesWave must be a string`);
  if (!STATES.has(raw.state as TicketState)) fail(`${where}.state "${String(raw.state)}" is invalid`);
  return raw as unknown as Spike;
}

/** Validates an untrusted parsed object into a typed `Board`. Throws on any
 *  structural problem so the host can fall back to an empty board + error. */
export function validateBoard(raw: unknown): Board {
  if (!isObject(raw)) fail("root must be an object");
  if (typeof raw.project !== "string") fail("project must be a string");
  if (typeof raw.generatedAt !== "string") fail("generatedAt must be a string");
  if (!Array.isArray(raw.spikes)) fail("spikes must be an array");
  if (!Array.isArray(raw.waves)) fail("waves must be an array");
  raw.spikes.forEach((s, i) => validateSpike(s, `spikes[${i}]`));
  raw.waves.forEach((w, i) => validateWave(w, `waves[${i}]`));
  return raw as unknown as Board;
}

/** Today's source: a committed JSON snapshot handed in already-parsed. */
export class SnapshotSource implements BoardSource {
  constructor(private readonly raw: unknown) {}
  load(): Board {
    return validateBoard(this.raw);
  }
}

/** Future live source (`@linear/sdk` + API key). Seam only — not built yet. */
export class LinearSdkSource implements BoardSource {
  load(): Board {
    throw new Error("LinearSdkSource not implemented — live Linear fetch lands in a later wave");
  }
}

/** Empty board for the error-fallback path (malformed/missing snapshot). */
export const EMPTY_BOARD: Board = { project: "", generatedAt: "", spikes: [], waves: [] };
